package growpanel

// Per-group method wiring. Generated by hand because Go doesn\'t have first-class
// "expose namespace of method references" — each method here forwards to the generated
// client. When you regenerate (after the spec changes), add new methods here so the
// ergonomic groups stay in sync.
//
// NOTE: this file references `gen.GetReportsMrr` etc. on the generated client. Those
// method names are produced by oapi-codegen from the operation paths; until you run
// `go generate` (or the install + oapi-codegen command in README.md), the
// internal/generated/ directory is empty and this file will fail to compile.
// That\'s expected — see README.md for first-time setup.

import (
	"context"

	gen "github.com/growpanel/growpanel-sdk-go/internal/generated"
)

// ---- Reports ----

func (g *reportsGroup) GetSummary(ctx context.Context, params *gen.GetReportsSummaryParams) (*gen.GetReportsSummaryResponse, error) {
	return g.c.GetReportsSummaryWithResponse(ctx, params)
}
func (g *reportsGroup) GetMrr(ctx context.Context, params *gen.GetReportsMrrParams) (*gen.GetReportsMrrResponse, error) {
	return g.c.GetReportsMrrWithResponse(ctx, params)
}
func (g *reportsGroup) GetMrrGrowth(ctx context.Context, params *gen.GetReportsMrrGrowthParams) (*gen.GetReportsMrrGrowthResponse, error) {
	return g.c.GetReportsMrrGrowthWithResponse(ctx, params)
}

// ... add the rest as you wire them. The pattern is:
//   func (g *<group>) <Method>(ctx, params) (*gen.<Op>Response, error) {
//       return g.c.<Op>WithResponse(ctx, params)
//   }
//
// For brevity, only the most-used Report methods are wired here as a template.
// After running generation and seeing the actual method names oapi-codegen emits,
// extend this file to expose every operation.
